package es.exceptioncoders.thepersonaltrainerclub.view.trainerManagement

import es.exceptioncoders.thepersonaltrainerclub.model.provider.ClassProviderImp
import es.exceptioncoders.thepersonaltrainerclub.model.provider.UserProviderImp
import es.exceptioncoders.thepersonaltrainerclub.model.usecase.TrainerManagementUseCase
import es.exceptioncoders.thepersonaltrainerclub.model.usecase.TrainerManagementUseCaseImp
import es.exceptioncoders.thepersonaltrainerclub.view.base.BasePresenter

class TrainerManagementActivityPresenter(private val mNavigator: TrainerManagementActivityContract.TrainerManagementViewNavigator<TrainerManagementActivityContract.TrainerManagementView>) : BasePresenter<TrainerManagementActivityContract.TrainerManagementView>(), TrainerManagementActivityContract.TrainerManagementViewPresenter<TrainerManagementActivityContract.TrainerManagementView> {
    val useCase: TrainerManagementUseCase = TrainerManagementUseCaseImp(UserProviderImp(), ClassProviderImp())

}